"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.agent_type import AgentType
    from openapi_client.model.cloud_agent import CloudAgent
    from openapi_client.model.enterprise_agent_all_of import EnterpriseAgentAllOf
    from openapi_client.model.enterprise_agent_all_of_error_details import EnterpriseAgentAllOfErrorDetails
    from openapi_client.model.group import Group
    globals()['AgentType'] = AgentType
    globals()['CloudAgent'] = CloudAgent
    globals()['EnterpriseAgentAllOf'] = EnterpriseAgentAllOf
    globals()['EnterpriseAgentAllOfErrorDetails'] = EnterpriseAgentAllOfErrorDetails
    globals()['Group'] = Group


class EnterpriseAgent(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('agent_state',): {
            'ONLINE': "Online",
            'OFFLINE': "Offline",
            'DISABLED': "Disabled",
        },
        ('ipv6_policy',): {
            'FORCE_IPV4': "FORCE_IPV4",
            'PREFER_IPV6': "PREFER_IPV6",
            'FORCE_IPV6': "FORCE_IPV6",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'agent_id': (int,),  # noqa: E501
            'agent_name': (str,),  # noqa: E501
            'agent_type': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'country_id': (str,),  # noqa: E501
            'ip_addresses': ([str],),  # noqa: E501
            'location': (str,),  # noqa: E501
            'groups': ([Group],),  # noqa: E501
            'hostname': (str,),  # noqa: E501
            'prefix': (str,),  # noqa: E501
            'enabled': (bool,),  # noqa: E501
            'network': (str,),  # noqa: E501
            'created_date': (datetime,),  # noqa: E501
            'last_seen': (datetime,),  # noqa: E501
            'agent_state': (str,),  # noqa: E501
            'verify_ssl_certificates': (bool,),  # noqa: E501
            'keep_browser_cache': (bool,),  # noqa: E501
            'utilization': (int,),  # noqa: E501
            'ipv6_policy': (str,),  # noqa: E501
            'target_for_tests': (str,),  # noqa: E501
            'public_ip_addresses': ([str],),  # noqa: E501
            'error_details': (EnterpriseAgentAllOfErrorDetails,),  # noqa: E501
            'account_groups': ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}],),  # noqa: E501
            'notification_rules': ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'agent_id': 'agentId',  # noqa: E501
        'agent_name': 'agentName',  # noqa: E501
        'agent_type': 'agentType',  # noqa: E501
        'country_id': 'countryId',  # noqa: E501
        'ip_addresses': 'ipAddresses',  # noqa: E501
        'location': 'location',  # noqa: E501
        'groups': 'groups',  # noqa: E501
        'hostname': 'hostname',  # noqa: E501
        'prefix': 'prefix',  # noqa: E501
        'enabled': 'enabled',  # noqa: E501
        'network': 'network',  # noqa: E501
        'created_date': 'createdDate',  # noqa: E501
        'last_seen': 'lastSeen',  # noqa: E501
        'agent_state': 'agentState',  # noqa: E501
        'verify_ssl_certificates': 'verifySslCertificates',  # noqa: E501
        'keep_browser_cache': 'keepBrowserCache',  # noqa: E501
        'utilization': 'utilization',  # noqa: E501
        'ipv6_policy': 'ipv6Policy',  # noqa: E501
        'target_for_tests': 'targetForTests',  # noqa: E501
        'public_ip_addresses': 'publicIpAddresses',  # noqa: E501
        'error_details': 'errorDetails',  # noqa: E501
        'account_groups': 'accountGroups',  # noqa: E501
        'notification_rules': 'notificationRules',  # noqa: E501
    }

    read_only_vars = {
    }

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """EnterpriseAgent - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            agent_id (int): unique ID of agent. [optional]  # noqa: E501
            agent_name (str): display name of the agent. [optional]  # noqa: E501
            agent_type (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            country_id (str): ISO-3166-1 alpha-2 country code of the agent. [optional]  # noqa: E501
            ip_addresses ([str]): array of ipAddress entries. [optional]  # noqa: E501
            location (str): location of the agent. [optional]  # noqa: E501
            groups ([Group]): [optional]  # noqa: E501
            hostname (str): fully qualified domain name of the agent. [optional]  # noqa: E501
            prefix (str): Network prefix, expressed in CIDR format. [optional]  # noqa: E501
            enabled (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            network (str): name of the autonomous system in which the Agent is found. [optional]  # noqa: E501
            created_date (datetime): yyyy-MM-dd hh:mm:ss, expressed in UTC. [optional]  # noqa: E501
            last_seen (datetime): yyyy-MM-dd hh:mm:ss, expressed in UTC. [optional]  # noqa: E501
            agent_state (str): [optional]  # noqa: E501
            verify_ssl_certificates (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            keep_browser_cache (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            utilization (int): shows overall utilization percentage. [optional]  # noqa: E501
            ipv6_policy (str): IP version policy. [optional]  # noqa: E501
            target_for_tests (str): target IP address or domain name representing test destination when agent is acting as a test target in an agent-to-agent test. [optional]  # noqa: E501
            public_ip_addresses ([str]): array of ipAddress entries. [optional]  # noqa: E501
            error_details (EnterpriseAgentAllOfErrorDetails): [optional]  # noqa: E501
            account_groups ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}]): list of account groups to which the agent is assigned, showing aid and accountGroupName fields. [optional]  # noqa: E501
            notification_rules ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}]): array of notification rule objects configured on agent. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)

        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """EnterpriseAgent - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            agent_id (int): unique ID of agent. [optional]  # noqa: E501
            agent_name (str): display name of the agent. [optional]  # noqa: E501
            agent_type (bool, date, datetime, dict, float, int, list, str, none_type): [optional]  # noqa: E501
            country_id (str): ISO-3166-1 alpha-2 country code of the agent. [optional]  # noqa: E501
            ip_addresses ([str]): array of ipAddress entries. [optional]  # noqa: E501
            location (str): location of the agent. [optional]  # noqa: E501
            groups ([Group]): [optional]  # noqa: E501
            hostname (str): fully qualified domain name of the agent. [optional]  # noqa: E501
            prefix (str): Network prefix, expressed in CIDR format. [optional]  # noqa: E501
            enabled (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            network (str): name of the autonomous system in which the Agent is found. [optional]  # noqa: E501
            created_date (datetime): yyyy-MM-dd hh:mm:ss, expressed in UTC. [optional]  # noqa: E501
            last_seen (datetime): yyyy-MM-dd hh:mm:ss, expressed in UTC. [optional]  # noqa: E501
            agent_state (str): [optional]  # noqa: E501
            verify_ssl_certificates (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            keep_browser_cache (bool): 1 for enabled, 0 for disabled. [optional]  # noqa: E501
            utilization (int): shows overall utilization percentage. [optional]  # noqa: E501
            ipv6_policy (str): IP version policy. [optional]  # noqa: E501
            target_for_tests (str): target IP address or domain name representing test destination when agent is acting as a test target in an agent-to-agent test. [optional]  # noqa: E501
            public_ip_addresses ([str]): array of ipAddress entries. [optional]  # noqa: E501
            error_details (EnterpriseAgentAllOfErrorDetails): [optional]  # noqa: E501
            account_groups ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}]): list of account groups to which the agent is assigned, showing aid and accountGroupName fields. [optional]  # noqa: E501
            notification_rules ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}]): array of notification rule objects configured on agent. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")

    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
              CloudAgent,
              EnterpriseAgentAllOf,
          ],
          'oneOf': [
          ],
        }
