"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError



class HttpTestAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('auth_type',): {
            'NONE': "NONE",
            'BASIC': "BASIC",
            'NTLM': "NTLM",
            'KERBEROS': "KERBEROS",
        },
        ('http_version',): {
            '1': 1,
            '2': 2,
        },
        ('ssl_version_id',): {
            '0': 0,
            '3': 3,
            '4': 4,
            '5': 5,
            '6': 6,
        },
    }

    validations = {
        ('http_target_time',): {
            'inclusive_maximum': 5000,
            'inclusive_minimum': 100,
        },
        ('http_time_limit',): {
            'inclusive_maximum': 5,
            'inclusive_minimum': 60,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'auth_type': (str,),  # noqa: E501
            'client_certificate': (str,),  # noqa: E501
            'content_regex': (str,),  # noqa: E501
            'desired_status_code': (str,),  # noqa: E501
            'download_limit': (int,),  # noqa: E501
            'dns_override': (str,),  # noqa: E501
            'follow_redirects': (bool,),  # noqa: E501
            'headers': ([str],),  # noqa: E501
            'http_version': (int,),  # noqa: E501
            'http_target_time': (int,),  # noqa: E501
            'http_time_limit': (int,),  # noqa: E501
            'password': (str,),  # noqa: E501
            'post_body': (str,),  # noqa: E501
            'ssl_version': (str,),  # noqa: E501
            'ssl_version_id': (int,),  # noqa: E501
            'url': (str,),  # noqa: E501
            'use_ntlm': (bool,),  # noqa: E501
            'user_agent': (str,),  # noqa: E501
            'username': (str,),  # noqa: E501
            'verify_certificate': (bool,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'auth_type': 'authType',  # noqa: E501
        'client_certificate': 'clientCertificate',  # noqa: E501
        'content_regex': 'contentRegex',  # noqa: E501
        'desired_status_code': 'desiredStatusCode',  # noqa: E501
        'download_limit': 'downloadLimit',  # noqa: E501
        'dns_override': 'dnsOverride',  # noqa: E501
        'follow_redirects': 'followRedirects',  # noqa: E501
        'headers': 'headers',  # noqa: E501
        'http_version': 'httpVersion',  # noqa: E501
        'http_target_time': 'httpTargetTime',  # noqa: E501
        'http_time_limit': 'httpTimeLimit',  # noqa: E501
        'password': 'password',  # noqa: E501
        'post_body': 'postBody',  # noqa: E501
        'ssl_version': 'sslVersion',  # noqa: E501
        'ssl_version_id': 'sslVersionId',  # noqa: E501
        'url': 'url',  # noqa: E501
        'use_ntlm': 'useNtlm',  # noqa: E501
        'user_agent': 'userAgent',  # noqa: E501
        'username': 'username',  # noqa: E501
        'verify_certificate': 'verifyCertificate',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """HttpTestAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            auth_type (str): HTTP Authentication type; defaults to NONE. [optional]  # noqa: E501
            client_certificate (str): String representation (containing newline characters) of client certificate, if used. [optional]  # noqa: E501
            content_regex (str): This field does not require escaping. [optional]  # noqa: E501
            desired_status_code (str): Set to the value you’re interested in retrieving.. [optional]  # noqa: E501
            download_limit (int): specify maximum number of bytes to download from the target object. [optional]  # noqa: E501
            dns_override (str): IP address to use for DNS override. [optional]  # noqa: E501
            follow_redirects (bool): set to 0 to not follow HTTP/301 or HTTP/302 redirect directives. Default is 1. [optional]  # noqa: E501
            headers ([str]): array of header strings `[\"header: value\", \"header2: value\"]`; use HTTP header values in this list. [optional]  # noqa: E501
            http_version (int): 2 for default (prefer HTTP/2), 1 for HTTP/1.1 only. [optional]  # noqa: E501
            http_target_time (int): target time for HTTP server completion; specified in milliseconds. [optional]  # noqa: E501
            http_time_limit (int): defaults to 5 seconds. [optional]  # noqa: E501
            password (str): password to be used for Basic/NTLM authentication. [optional]  # noqa: E501
            post_body (str): Enter the post body in this field. No escaping is required. If the post body is set to something other than empty, the requestMethod will be set to POST.. [optional]  # noqa: E501
            ssl_version (str): Read Only; corresponds to sslVersionId; Reflects the verbose ssl protocol version used by a test. [optional]  # noqa: E501
            ssl_version_id (int): 0 for auto, 3 for SSLv3, 4 for TLS v1.0, 5 for TLS v1.1, 6 for TLS v1.2. [optional]  # noqa: E501
            url (str): target for the test. [optional]  # noqa: E501
            use_ntlm (bool): choose 1 to use NTLM, 0 to use Basic Authentication. Requires username/password to be set. [optional]  # noqa: E501
            user_agent (str): user-agent string to be provided during the test. [optional]  # noqa: E501
            username (str): username to be used for Basic/NTLM authentication. [optional]  # noqa: E501
            verify_certificate (bool): set to 0 to ignore certificate errors (defaults to 1). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """HttpTestAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            auth_type (str): HTTP Authentication type; defaults to NONE. [optional]  # noqa: E501
            client_certificate (str): String representation (containing newline characters) of client certificate, if used. [optional]  # noqa: E501
            content_regex (str): This field does not require escaping. [optional]  # noqa: E501
            desired_status_code (str): Set to the value you’re interested in retrieving.. [optional]  # noqa: E501
            download_limit (int): specify maximum number of bytes to download from the target object. [optional]  # noqa: E501
            dns_override (str): IP address to use for DNS override. [optional]  # noqa: E501
            follow_redirects (bool): set to 0 to not follow HTTP/301 or HTTP/302 redirect directives. Default is 1. [optional]  # noqa: E501
            headers ([str]): array of header strings `[\"header: value\", \"header2: value\"]`; use HTTP header values in this list. [optional]  # noqa: E501
            http_version (int): 2 for default (prefer HTTP/2), 1 for HTTP/1.1 only. [optional]  # noqa: E501
            http_target_time (int): target time for HTTP server completion; specified in milliseconds. [optional]  # noqa: E501
            http_time_limit (int): defaults to 5 seconds. [optional]  # noqa: E501
            password (str): password to be used for Basic/NTLM authentication. [optional]  # noqa: E501
            post_body (str): Enter the post body in this field. No escaping is required. If the post body is set to something other than empty, the requestMethod will be set to POST.. [optional]  # noqa: E501
            ssl_version (str): Read Only; corresponds to sslVersionId; Reflects the verbose ssl protocol version used by a test. [optional]  # noqa: E501
            ssl_version_id (int): 0 for auto, 3 for SSLv3, 4 for TLS v1.0, 5 for TLS v1.1, 6 for TLS v1.2. [optional]  # noqa: E501
            url (str): target for the test. [optional]  # noqa: E501
            use_ntlm (bool): choose 1 to use NTLM, 0 to use Basic Authentication. Requires username/password to be set. [optional]  # noqa: E501
            user_agent (str): user-agent string to be provided during the test. [optional]  # noqa: E501
            username (str): username to be used for Basic/NTLM authentication. [optional]  # noqa: E501
            verify_certificate (bool): set to 0 to ignore certificate errors (defaults to 1). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
