"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.server_test_all_of_agents import ServerTestAllOfAgents
    from openapi_client.model.server_test_all_of_bgp_monitors import ServerTestAllOfBgpMonitors
    from openapi_client.model.test_interval import TestInterval
    globals()['ServerTestAllOfAgents'] = ServerTestAllOfAgents
    globals()['ServerTestAllOfBgpMonitors'] = ServerTestAllOfBgpMonitors
    globals()['TestInterval'] = TestInterval


class ServerTestAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('path_trace_mode',): {
            'CLASSIC': "classic",
            'INSESSION': "inSession",
        },
        ('probe_mode',): {
            'AUTO': "AUTO",
            'SACK': "SACK",
            'SYN': "SYN",
        },
        ('protocol',): {
            'ICMP': "ICMP",
            'TCP': "TCP",
        },
    }

    validations = {
        ('num_path_traces',): {
            'inclusive_maximum': 3,
            'inclusive_minimum': 10,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'agents': ([ServerTestAllOfAgents],),  # noqa: E501
            'bandwidth_measurements': (bool,),  # noqa: E501
            'bgp_measurements': (bool,),  # noqa: E501
            'bgp_monitors': ([ServerTestAllOfBgpMonitors],),  # noqa: E501
            'interval': (TestInterval,),  # noqa: E501
            'mtu_measurements': (bool,),  # noqa: E501
            'network_measurements': (bool,),  # noqa: E501
            'num_path_traces': (int,),  # noqa: E501
            'path_trace_mode': (str,),  # noqa: E501
            'probe_mode': (str,),  # noqa: E501
            'protocol': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'agents': 'agents',  # noqa: E501
        'bandwidth_measurements': 'bandwidthMeasurements',  # noqa: E501
        'bgp_measurements': 'bgpMeasurements',  # noqa: E501
        'bgp_monitors': 'bgpMonitors',  # noqa: E501
        'interval': 'interval',  # noqa: E501
        'mtu_measurements': 'mtuMeasurements',  # noqa: E501
        'network_measurements': 'networkMeasurements',  # noqa: E501
        'num_path_traces': 'numPathTraces',  # noqa: E501
        'path_trace_mode': 'pathTraceMode',  # noqa: E501
        'probe_mode': 'probeMode',  # noqa: E501
        'protocol': 'protocol',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ServerTestAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            agents ([ServerTestAllOfAgents]): array of agent objects `{\"agentId\": agentId}`; get agentId from /agents endpoint.. [optional]  # noqa: E501
            bandwidth_measurements (bool): set to 1 to measure bandwidth. Only applies to Enterprise Agents assigned to the test, and requires that networkMeasurements is set.. [optional]  # noqa: E501
            bgp_measurements (bool): choose 1 to enable bgp measurements, 0 to disable; defaults to 1 when networkMeasurements is set. [optional]  # noqa: E501
            bgp_monitors ([ServerTestAllOfBgpMonitors]): array of BGP Monitor objects `{\"monitorId\": monitorId}`; get monitorId from /bgp-monitors endpoint.. [optional]  # noqa: E501
            interval (TestInterval): [optional]  # noqa: E501
            mtu_measurements (bool): set to 1 to measure MTU sizes on network from agents to the target. [optional]  # noqa: E501
            network_measurements (bool): choose 1 to enable network measurements, 0 to disable; defaults to 1. [optional]  # noqa: E501
            num_path_traces (int): defaults to 3. [optional]  # noqa: E501
            path_trace_mode (str): choose `inSession` to perform the path trace within a TCP session; defaults to `classic`. [optional]  # noqa: E501
            probe_mode (str): probe mode used by End-to-end Network Test; only valid if `protocol` is set to `TCP`; defaults to `AUTO`. [optional]  # noqa: E501
            protocol (str): protocol used by dependent Network tests (End-to-end, Path Trace, PMTUD); defaults to `TCP`. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ServerTestAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            agents ([ServerTestAllOfAgents]): array of agent objects `{\"agentId\": agentId}`; get agentId from /agents endpoint.. [optional]  # noqa: E501
            bandwidth_measurements (bool): set to 1 to measure bandwidth. Only applies to Enterprise Agents assigned to the test, and requires that networkMeasurements is set.. [optional]  # noqa: E501
            bgp_measurements (bool): choose 1 to enable bgp measurements, 0 to disable; defaults to 1 when networkMeasurements is set. [optional]  # noqa: E501
            bgp_monitors ([ServerTestAllOfBgpMonitors]): array of BGP Monitor objects `{\"monitorId\": monitorId}`; get monitorId from /bgp-monitors endpoint.. [optional]  # noqa: E501
            interval (TestInterval): [optional]  # noqa: E501
            mtu_measurements (bool): set to 1 to measure MTU sizes on network from agents to the target. [optional]  # noqa: E501
            network_measurements (bool): choose 1 to enable network measurements, 0 to disable; defaults to 1. [optional]  # noqa: E501
            num_path_traces (int): defaults to 3. [optional]  # noqa: E501
            path_trace_mode (str): choose `inSession` to perform the path trace within a TCP session; defaults to `classic`. [optional]  # noqa: E501
            probe_mode (str): probe mode used by End-to-end Network Test; only valid if `protocol` is set to `TCP`; defaults to `AUTO`. [optional]  # noqa: E501
            protocol (str): protocol used by dependent Network tests (End-to-end, Path Trace, PMTUD); defaults to `TCP`. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
