"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.enterprise_agent_all_of_error_details import EnterpriseAgentAllOfErrorDetails


class TestEnterpriseAgentAllOfErrorDetails(unittest.TestCase):
    """EnterpriseAgentAllOfErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseAgentAllOfErrorDetails(self):
        """Test EnterpriseAgentAllOfErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseAgentAllOfErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
