"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.agents__monitors_api import AgentsMonitorsApi  # noqa: E501


class TestAgentsMonitorsApi(unittest.TestCase):
    """AgentsMonitorsApi unit test stubs"""

    def setUp(self):
        self.api = AgentsMonitorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_agents_agent_id_get(self):
        """Test case for agents_agent_id_get

        Returns details for an agent, including assigned tests.  # noqa: E501
        """
        pass

    def test_agents_get(self):
        """Test case for agents_get

        Returns a list of all agents available to your account in ThousandEyes, including both Enterprise and Cloud agents.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
