"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.group_details import GroupDetails
globals()['GroupDetails'] = GroupDetails
from openapi_client.model.inline_response201 import InlineResponse201


class TestInlineResponse201(unittest.TestCase):
    """InlineResponse201 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201(self):
        """Test InlineResponse201"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse201()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
