"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.test_interval import TestInterval


class TestTestInterval(unittest.TestCase):
    """TestInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestInterval(self):
        """Test TestInterval"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestInterval()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
