"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_test_shared_with_accounts import BaseTestSharedWithAccounts


class TestBaseTestSharedWithAccounts(unittest.TestCase):
    """BaseTestSharedWithAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseTestSharedWithAccounts(self):
        """Test BaseTestSharedWithAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseTestSharedWithAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
