"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.groups_type_new_agents import GroupsTypeNewAgents
from openapi_client.model.groups_type_new_tests import GroupsTypeNewTests
globals()['GroupsTypeNewAgents'] = GroupsTypeNewAgents
globals()['GroupsTypeNewTests'] = GroupsTypeNewTests
from openapi_client.model.inline_object1 import InlineObject1


class TestInlineObject1(unittest.TestCase):
    """InlineObject1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject1(self):
        """Test InlineObject1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
