"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.integration_pager_duty_all_of import IntegrationPagerDutyAllOf


class TestIntegrationPagerDutyAllOf(unittest.TestCase):
    """IntegrationPagerDutyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationPagerDutyAllOf(self):
        """Test IntegrationPagerDutyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrationPagerDutyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
