"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_test import ServerTest


class TestServerTest(unittest.TestCase):
    """ServerTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerTest(self):
        """Test ServerTest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerTest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
