"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.alerts__notifications_api import AlertsNotificationsApi  # noqa: E501


class TestAlertsNotificationsApi(unittest.TestCase):
    """AlertsNotificationsApi unit test stubs"""

    def setUp(self):
        self.api = AlertsNotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alert_rules_get(self):
        """Test case for alert_rules_get

        Returns a list of all alert rules configured under your account in ThousandEyes.  # noqa: E501
        """
        pass

    def test_alert_rules_new_post(self):
        """Test case for alert_rules_new_post

        Creates a new alert rule in your account, based on properties provided in the POST data.  # noqa: E501
        """
        pass

    def test_alert_rules_rule_id_delete_post(self):
        """Test case for alert_rules_rule_id_delete_post

        Deletes an alert rule in your account.  # noqa: E501
        """
        pass

    def test_alert_rules_rule_id_get(self):
        """Test case for alert_rules_rule_id_get

        Returns details about an alert rule.  # noqa: E501
        """
        pass

    def test_alert_rules_rule_id_update_post(self):
        """Test case for alert_rules_rule_id_update_post

        Modifies an existing alert rule in your account, based on properties provided in the POST data.  # noqa: E501
        """
        pass

    def test_alerts_alert_id_get(self):
        """Test case for alerts_alert_id_get

        Returns details about an alert.  # noqa: E501
        """
        pass

    def test_alerts_get(self):
        """Test case for alerts_get

        Returns a list of all active alerts, active at any given time.  # noqa: E501
        """
        pass

    def test_integrations_get(self):
        """Test case for integrations_get

        Returns a list of all alert notification integrations (webhooks, PagerDuty, Slack, …)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
