"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_test import BaseTest
globals()['BaseTest'] = BaseTest
from openapi_client.model.alert_rule_detail_all_of import AlertRuleDetailAllOf


class TestAlertRuleDetailAllOf(unittest.TestCase):
    """AlertRuleDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertRuleDetailAllOf(self):
        """Test AlertRuleDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertRuleDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
