"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.labels_api import LabelsApi  # noqa: E501


class TestLabelsApi(unittest.TestCase):
    """LabelsApi unit test stubs"""

    def setUp(self):
        self.api = LabelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_get(self):
        """Test case for groups_get

        Returns a list of all labels (formerly called groups) configured in ThousandEyes.  # noqa: E501
        """
        pass

    def test_groups_group_id_delete_post(self):
        """Test case for groups_group_id_delete_post

        Deletes a label (formerly called group) currently configured in ThousandEyes.  # noqa: E501
        """
        pass

    def test_groups_group_id_get(self):
        """Test case for groups_group_id_get

        Returns details for a label (formerly called group) configured in ThousandEyes.  # noqa: E501
        """
        pass

    def test_groups_group_id_update_post(self):
        """Test case for groups_group_id_update_post

        Updates a label (formerly called group) in ThousandEyes, based on properties provided in the POST data.  # noqa: E501
        """
        pass

    def test_groups_type_get(self):
        """Test case for groups_type_get

        Returns a list of all tests of the label (formerly called group) type specified, configured in ThousandEyes.  # noqa: E501
        """
        pass

    def test_groups_type_group_id_get(self):
        """Test case for groups_type_group_id_get

        Returns a list of all labels (formerly called groups) configured in ThousandEyes.  # noqa: E501
        """
        pass

    def test_groups_type_new_post(self):
        """Test case for groups_type_new_post

        Creates a new label (formerly called group) in ThousandEyes, based on properties provided in the POST data.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
