"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.agent_id import AgentId
from openapi_client.model.agent_name import AgentName
from openapi_client.model.agent_state import AgentState
from openapi_client.model.error_details import ErrorDetails
from openapi_client.model.ip_addresses import IpAddresses
from openapi_client.model.last_seen import LastSeen
from openapi_client.model.network import Network
from openapi_client.model.prefix import Prefix
from openapi_client.model.public_ip_addresses import PublicIpAddresses
from openapi_client.model.target_for_tests import TargetForTests
globals()['AgentId'] = AgentId
globals()['AgentName'] = AgentName
globals()['AgentState'] = AgentState
globals()['ErrorDetails'] = ErrorDetails
globals()['IpAddresses'] = IpAddresses
globals()['LastSeen'] = LastSeen
globals()['Network'] = Network
globals()['Prefix'] = Prefix
globals()['PublicIpAddresses'] = PublicIpAddresses
globals()['TargetForTests'] = TargetForTests
from openapi_client.model.enterprise_cluster_member import EnterpriseClusterMember


class TestEnterpriseClusterMember(unittest.TestCase):
    """EnterpriseClusterMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseClusterMember(self):
        """Test EnterpriseClusterMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseClusterMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
