"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.base_test import BaseTest
from openapi_client.model.base_test_alert_rules import BaseTestAlertRules
from openapi_client.model.base_test_api_links import BaseTestApiLinks
from openapi_client.model.base_test_shared_with_accounts import BaseTestSharedWithAccounts
from openapi_client.model.group import Group
from openapi_client.model.shareable_test_all_of import ShareableTestAllOf
from openapi_client.model.test_type import TestType
globals()['BaseTest'] = BaseTest
globals()['BaseTestAlertRules'] = BaseTestAlertRules
globals()['BaseTestApiLinks'] = BaseTestApiLinks
globals()['BaseTestSharedWithAccounts'] = BaseTestSharedWithAccounts
globals()['Group'] = Group
globals()['ShareableTestAllOf'] = ShareableTestAllOf
globals()['TestType'] = TestType
from openapi_client.model.shareable_test import ShareableTest


class TestShareableTest(unittest.TestCase):
    """ShareableTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShareableTest(self):
        """Test ShareableTest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShareableTest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
