"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.agent_to_server_test import AgentToServerTest
from openapi_client.model.group import Group
from openapi_client.model.group_details_all_of import GroupDetailsAllOf
from openapi_client.model.group_type import GroupType
from openapi_client.model.http_test import HttpTest
globals()['AgentToServerTest'] = AgentToServerTest
globals()['Group'] = Group
globals()['GroupDetailsAllOf'] = GroupDetailsAllOf
globals()['GroupType'] = GroupType
globals()['HttpTest'] = HttpTest
from openapi_client.model.group_details import GroupDetails


class TestGroupDetails(unittest.TestCase):
    """GroupDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupDetails(self):
        """Test GroupDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
