"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_obj import AlertObj


class TestAlertObj(unittest.TestCase):
    """AlertObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertObj(self):
        """Test AlertObj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertObj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
