"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.test_type import TestType


class TestTestType(unittest.TestCase):
    """TestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestType(self):
        """Test TestType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
