"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.integration_slack_all_of import IntegrationSlackAllOf


class TestIntegrationSlackAllOf(unittest.TestCase):
    """IntegrationSlackAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationSlackAllOf(self):
        """Test IntegrationSlackAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrationSlackAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
