"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_rule_email import AlertRuleEmail
from openapi_client.model.integration_pager_duty import IntegrationPagerDuty
from openapi_client.model.integration_slack import IntegrationSlack
from openapi_client.model.integration_webhook import IntegrationWebhook
globals()['AlertRuleEmail'] = AlertRuleEmail
globals()['IntegrationPagerDuty'] = IntegrationPagerDuty
globals()['IntegrationSlack'] = IntegrationSlack
globals()['IntegrationWebhook'] = IntegrationWebhook
from openapi_client.model.alert_rule_notifications import AlertRuleNotifications


class TestAlertRuleNotifications(unittest.TestCase):
    """AlertRuleNotifications unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertRuleNotifications(self):
        """Test AlertRuleNotifications"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertRuleNotifications()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
