"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.integration_pager_duty import IntegrationPagerDuty


class TestIntegrationPagerDuty(unittest.TestCase):
    """IntegrationPagerDuty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationPagerDuty(self):
        """Test IntegrationPagerDuty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrationPagerDuty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
