"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_groups import AccountGroups
from openapi_client.model.created_date import CreatedDate
from openapi_client.model.enabled import Enabled
from openapi_client.model.enterprise_cluster_member import EnterpriseClusterMember
from openapi_client.model.error_details import ErrorDetails
from openapi_client.model.ipv6_policy import Ipv6Policy
from openapi_client.model.keep_browser_cache import KeepBrowserCache
from openapi_client.model.notification_rules import NotificationRules
from openapi_client.model.verify_ssl_certificates import VerifySslCertificates
globals()['AccountGroups'] = AccountGroups
globals()['CreatedDate'] = CreatedDate
globals()['Enabled'] = Enabled
globals()['EnterpriseClusterMember'] = EnterpriseClusterMember
globals()['ErrorDetails'] = ErrorDetails
globals()['Ipv6Policy'] = Ipv6Policy
globals()['KeepBrowserCache'] = KeepBrowserCache
globals()['NotificationRules'] = NotificationRules
globals()['VerifySslCertificates'] = VerifySslCertificates
from openapi_client.model.enterprise_cluster_agent_all_of import EnterpriseClusterAgentAllOf


class TestEnterpriseClusterAgentAllOf(unittest.TestCase):
    """EnterpriseClusterAgentAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseClusterAgentAllOf(self):
        """Test EnterpriseClusterAgentAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseClusterAgentAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
