"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_test_all_of_agents import ServerTestAllOfAgents
from openapi_client.model.server_test_all_of_bgp_monitors import ServerTestAllOfBgpMonitors
from openapi_client.model.test_interval import TestInterval
globals()['ServerTestAllOfAgents'] = ServerTestAllOfAgents
globals()['ServerTestAllOfBgpMonitors'] = ServerTestAllOfBgpMonitors
globals()['TestInterval'] = TestInterval
from openapi_client.model.server_test_all_of import ServerTestAllOf


class TestServerTestAllOf(unittest.TestCase):
    """ServerTestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerTestAllOf(self):
        """Test ServerTestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerTestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
