"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_api_links import AlertApiLinks
from openapi_client.model.alert_obj import AlertObj
globals()['AlertApiLinks'] = AlertApiLinks
globals()['AlertObj'] = AlertObj
from openapi_client.model.alert import Alert


class TestAlert(unittest.TestCase):
    """Alert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlert(self):
        """Test Alert"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Alert()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
