"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.status_api import StatusApi  # noqa: E501


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        This returns the current controller time (in epoch format)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
