"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_monitor_obj_all_of import AlertMonitorObjAllOf


class TestAlertMonitorObjAllOf(unittest.TestCase):
    """AlertMonitorObjAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertMonitorObjAllOf(self):
        """Test AlertMonitorObjAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertMonitorObjAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
