"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.enterprise_cluster_agent import EnterpriseClusterAgent


class TestEnterpriseClusterAgent(unittest.TestCase):
    """EnterpriseClusterAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnterpriseClusterAgent(self):
        """Test EnterpriseClusterAgent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnterpriseClusterAgent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
