"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alert_agent_obj_all_of import AlertAgentObjAllOf
from openapi_client.model.alert_obj import AlertObj
globals()['AlertAgentObjAllOf'] = AlertAgentObjAllOf
globals()['AlertObj'] = AlertObj
from openapi_client.model.alert_agent_obj import AlertAgentObj


class TestAlertAgentObj(unittest.TestCase):
    """AlertAgentObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertAgentObj(self):
        """Test AlertAgentObj"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AlertAgentObj()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
