"""
    Thousand Eyes API V6

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 6.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.integration_obj import IntegrationObj
globals()['IntegrationObj'] = IntegrationObj
from openapi_client.model.inline_response2007_integrations import InlineResponse2007Integrations


class TestInlineResponse2007Integrations(unittest.TestCase):
    """InlineResponse2007Integrations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007Integrations(self):
        """Test InlineResponse2007Integrations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2007Integrations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
